server:
  port: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://140.143.154.143:8761/eureka/
zuul:
  add-host-header: true
  ignored-services: '*'
  retryable: true
  routes:
   api-user:
      path: /user/**
      serviceId:  pan-provider-user
 